// We require the Hardhat Runtime Environment explicitly here. This is optional
// but useful for running the script in a standalone fashion through `node <script>`.
//
// When running the script with `npx hardhat run <script>` you'll find the Hardhat
// Runtime Environment's members available in the global scope.
const hre = require("hardhat");

let names = [
  "Marfu",
  "Sunuguk",
  "Dakgu",
  "Quomaugh",
  "Trugagh",
  "Sakgu",
  "Hebub",
  "Zargulg",
  "Holkurg",
  "Ughash",
  "Omaghed",
  "Rogan",
  "Squagan",
  "Yambagorn",
  "Jukha",
  "Supaugh",
  "Umhra",
  "Vubub",
  "Brugo",
  "Bumhug",
  "Vorgak",
  "Xugug",
  "Snaglak",
  "Vretkag",
  "Wumkbanok",
  "Zarod",
  "Lumdum",
  "Guthakug",
  "Noogugh",
  "Bogugh",
  "Jugag",
  "Bagamul",
  "Karthurg",
  "Kukgilug",
  "Graman",
  "Baghig",
  "Buadagh",
  "Barfu",
  "Mahk",
  "Faghig",
  "Gutjja",
  "Kraugug",
  "Tagdud",
  "Duma",
  "Bruigig",
  "Tarod",
  "Gorlag",
  "Balogog",
  "Opoguk",
  "Xutag",
  "Urgran",
  "Omugug",
  "Yagnar",
  "Sugarod",
  "Murbag",
  "Kebub",
  "Kulgha",
  "Guthug",
  "Vrigka",
  "Wurgoth",
  "Argigoth",
  "Zurghed",
  "Ulgan",
  "Xolkug",
  "Fozhug",
  "Hokulk",
  "Ogrul",
  "Karrhig",
  "Sodagh",
  "Orpigig",
  "Xothkug",
  "Urbul",
  "Olog",
  "Yulakgh",
  "Lorbumol",
  "Speghat",
  "Gujjab",
  "Borkul",
  "Fudhagh",
  "Vrograg",
  "Pregu",
  "Numhug",
  "Guarg",
  "Xegug",
  "Bugdul",
  "Zlog",
  "Hogug",
  "Hugmug",
  "Otugbu",
  "Xutjja",
  "Gulm",
  "Kabugbu",
  "Taghig",
  "Ugghra",
  "Wudhagh",
  "Wokganit",
  "Xunug",
  "Grukk",
  "Dakgorim",
  "Nehrakgu",
  "Muzgonk",
  "Wrukag",
  "Sornaraugh",
  "Maknok",
  "Wurthu",
  "Oggha",
  "Gnarlug",
  "Zugorim",
  "Yagnatz",
  "Xorakk",
  "Jokgagu",
  "Slughig",
  "Wudgh",
  "Viggu",
  "Sabub",
  "Gnurl",
  "Wonabadug",
  "Routhu",
  "Rugbu",
  "Zornaraugh",
  "Xonoth",
  "Sguk",
  "Spathu",
  "Zguk",
  "Sulmthu",
  "Ghazat",
  "Klapdud",
  "Krothu",
  "Fogugh",
  "Paghorim",
  "Shargam",
  "Dul",
  "Slodagh",
  "Eggugat",
  "Sharkub",
  "Carguk",
  "Inkathu",
  "Ungagh",
  "Dregu",
  "Yargug",
  "Yroh",
  "Kurz",
  "Xugaa",
  "Fodagog",
  "Murag",
  "Mazhug",
  "Ug",
  "Xaguk",
  "Zurgug",
  "Todagog",
  "Bugak",
  "Omegugh",
  "Grukag",
  "Traugh",
  "Wurmha",
  "Garzonk",
  "Hagu",
  "Uzul",
  "Mash",
  "Turbag",
  "Nomgulg",
  "Rugdumph",
  "Bakh",
  "Gogron",
  "Hanso",
  "Ieul",
  "Jusduil",
  "Ilraion",
  "Mandmith",
  "Nor",
  "Aeron",
  "Rinree",
  "Uilaselen",
  "Orfan",
  "Drinro",
  "Ae",
  "Dirga",
  "Tyimgor",
  "Lorgo",
  "Naswe",
  "Hatha",
  "Kithladhir",
  "Bornrohir",
  "Tinuha",
  "Rian",
  "Liate",
  "Duelen",
  "Jusev",
  "Rianran",
  "Shaneltho",
  "Gaev",
  "Saelsa",
  "Gone",
  "Eddis",
  "Belegmel",
  "Ladel",
  "Thrannas",
  "Nardra",
  "Haddhel",
  "Andar",
  "Anaphia",
  "Daneres",
  "Morilleelos",
  "Arthane",
  "Losed",
  "Iondin",
  "Aedol",
  "Duve",
  "Ingphor",
  "Phiamor",
  "Drisaz",
  "Tyrian",
  "Nede",
  "Linfan",
  "Thasmor",
  "Dar",
  "Arantoror",
  "Bregthal",
  "Imgorthorn",
  "Eathane",
  "Fukur",
  "Khansar",
  "Dorlan",
  "Shimtar",
  "Lolee",
  "Meria",
  "Aewen",
  "Athand",
  "Kaelphor",
  "Ratari",
  "Tabeleg",
  "Kraeste",
  "Dorthe",
  "Rielsael",
  "Ren",
  "Nasdol",
  "Daenor",
  "Thasriel",
  "Randriel",
  "Renpen",
  "Drilpa",
  "Dhelthe",
  "Auil",
  "Ekael",
  "Mihel",
  "Marme",
  "Amarrond",
  "Ca",
  "Thordrilfeu",
  "Giwe",
  "Dielles",
  "Maren",
  "Ramel",
  "Leonbeleg",
  "Kiththalion",
  "Kaelmiel",
  "Larian",
  "Halbreg",
  "Erilkael",
  "Dorsar",
  "Leede",
  "Gwinrien",
  "Diranor",
  "Losla",
  "Mandtha",
  "Imlor",
  "Dhonshan",
  "Bojus",
  "Dehfind",
  "Tethorn",
  "Resleon",
  "Ela",
  "Suae",
  "Soion",
  "Satha",
  "Nerrin",
  "Altabara",
  "Drilmath",
  "Gakael",
  "Ieaeg",
  "Borriel",
  "Dalmi",
  "Wenthalbeleg",
  "Ionnas",
  "Rionviuswen",
  "Xathas",
  "Thalionuila",
  "Anaand",
  "Markith",
  "Ingen",
  "Habel",
  "Taegil",
  "Celeana",
  "Nasron",
  "Hadkael",
  "Andkith",
  "Losdin",
  "Drinthe",
  "Lasvo",
  "Imorear",
  "Dalaeg",
  "Ilglor",
  "Barada",
  "Reth",
  "Pendhel",
  "Taphant",
  "Dhel",
  "Dave",
  "Dehthil",
  "Traran",
  "Dordis",
  "Ranas",
  "Zentinu",
  "Thandis",
  "Morilril",
  "Golfe",
  "Marreth",
  "Eresuil",
  "Gomai",
  "Enras",
  "Uilphor",
  "Dielria",
  "Evrilev",
  "Ceuilas",
  "Adel",
  "Althas",
  "Ingdel",
  "Lethfin",
  "Lassael",
  "Rianthi",
  "Dan",
  "Moredhel",
  "Kurdalor",
  "Erilja",
  "Arril",
  "Kraesa",
  "Malmai",
  "Orbri",
  "Azdhros",
  "Torormo",
  "Shihir",
  "Araen",
  "Tehel",
  "Finae",
  "Dris",
  "Dingil",
  "Evedhel",
  "Rabor",
  "Galgil",
  "Laner",
  "Halma",
  "Merilren",
  "Fe",
  "Kraesril",
  "Thelfinae",
  "Dwyra",
  "Rondir",
  "Mithar",
  "Halmeril",
  "Kraesshim",
  "Thresal",
  "Curutoror",
  "Erilgnor",
  "Racir",
  "Thelcir",
  "Ieiel",
  "Eagal",
  "Galadhdor",
  "Maedris",
  "Pena",
  "Malla",
  "Dir",
  "Malbeleg",
  "Wennor",
  "Loredhel",
  "Futar",
  "Irdra",
  "Liaros",
  "Dedral",
  "Arbeleg",
  "Lasil",
  "Riantha",
  "Sarfind",
  "Dirlos",
  "Thaslad",
  "Rego",
  "Eresae",
  "Cururiel",
  "Fuil",
  "Fanra",
  "Mawen",
  "Leda",
  "Ladceleb",
  "Wen",
  "Thornlal",
  "Dalfind",
  "Miththan",
  "Lordrane",
  "Dashi",
  "Barawe",
  "Drilgo",
  "Levius",
  "Rasthas",
  "Thedra",
  "Anaadan",
  "Cuva",
  "Felae",
  "Mararaen",
  "Vamith",
  "Teron",
  "Baravar",
  "Rondvo",
  "Wingwe",
  "Penlas",
  "Nedir",
  "Shidir",
  "Dalas",
  "Rilae",
  "Nephant",
  "Thalshi",
  "Fananor",
  "Dreldirlor",
  "Irla",
  "Me",
  "Thitor",
  "Disrandirthal",
  "Dorcuru",
  "Rogwin",
  "Lo",
  "Aerohir",
  "Mar",
  "Mithvius",
  "Imorthir",
  "Hathres",
  "Drane",
  "Dordris",
  "Anorea",
  "Argwin",
  "Morilaz",
  "Losto",
  "Nimwing",
  "Dirloran",
  "Rores",
  "Drinreth",
  "Dudar",
  "Vashjgol",
  "Finle",
  "Thedin",
  "Taca",
  "Aranlan",
  "Lostarire",
  "Iondag",
  "Endin",
  "Leetarsyl",
  "Dolmar",
  "Hirriel",
  "Shan",
  "Vashjvo",
  "Dralfe",
  "Erilrine",
  "Rille",
  "Thahir",
  "Larin",
  "Moed",
  "Vaglor",
  "Andmi",
  "Tava",
  "Ronda",
  "Thelvashj",
  "Dril",
  "Maee",
  "Finthorn",
  "Losloran",
  "Tosyl",
  "Mala",
  "Raed",
  "Ion",
  "Al",
  "Trale",
  "Lavius",
  "Theldhros",
  "Cirla",
  "Haltoror",
  "Lorthran",
  "Thirmith",
  "Dorlal",
  "Sarrom",
  "Tha",
  "Romsyl",
  "Lasrian",
  "Rohirborn",
  "Moda",
  "Loslas",
  "Dwyrmar",
  "Quengaladh",
  "Armo",
  "Phortarmor",
  "Raentari",
  "Phormor",
  "Aela",
  "Mithbreg",
  "Fanaeg",
  "Motororja",
  "Thir",
  "Aete",
  "Gacaror",
  "Adan",
  "Shi",
  "Sarglor",
  "Ciras",
  "Salia",
  "Phiafan",
  "Elos",
  "Baraaeg",
  "Ea",
  "Iorcuruma",
  "Dalsu",
  "Rommel",
  "Shimree",
  "Liapa",
  "Mardir",
  "Uildan",
  "Sacar",
  "Rethquen",
  "Disdhrossa",
  "Phantthilthan",
  "Rosle",
  "Rianthandron",
  "Loas",
  "Orsar",
  "Malelen",
  "Vane",
  "Gilta",
  "Tele",
  "Tororre",
  "Wingthil",
  "Halrien",
  "Thidel",
  "Ordiel",
  "Ranmara",
  "Mailascir",
  "Vafela",
  "Wetar",
  "Phorhir",
  "Rondthran",
  "Immel",
  "Gohad",
  "Gota",
  "Morthandtinu",
  "Galadhriel",
  "Thil",
  "Irlin",
  "Belthir",
  "Celedae",
  "Rodsael",
  "Morilha",
  "Athres",
  "Bornlos",
  "Gathe",
  "Vanshan",
  "Ra",
  "Cir",
  "Dranevaar",
  "Ta",
  "Dralrion",
  "Evcurudrane",
  "Mothal",
  "Borreth",
  "Dannasgriel",
  "Thurincir",
  "Aegdra",
  "Belegria",
  "Dor",
  "Lethwen",
  "Glorsar",
  "Fingi",
  "Halthurin",
  "Rondana",
  "Amara",
  "Thele",
  "Leondrin",
  "Dirda",
  "Adanlos",
  "Moion",
  "Vo",
  "Taeta",
  "Norgriel",
  "Thelron",
  "Disva",
  "Mobri",
  "Doldae",
  "Borndol",
  "Tediel",
  "Tarel",
  "Rohircir",
  "Kurmae",
  "Tho",
  "Evardhros",
  "Raa",
  "Rathe",
  "Varrtha",
  "Penria",
  "Dolfin",
  "Lorana",
  "Leimor",
  "Onithorn",
  "Barael",
  "Bornria",
  "Bornthenas",
  "Edvaar",
  "Enlos",
  "Rantor",
  "Daalta",
  "Rale",
  "Reevar",
  "Bregfin",
  "Daamar",
  "Traana",
  "Imorgwin",
  "Lor",
  "Grielir",
  "Thornvaar",
  "Rielran",
  "Marthe",
  "Dagthi",
  "Sarhel",
  "Radir",
  "Dal",
  "Vene",
  "Taeduil",
  "Kaelrin",
  "Helphor",
  "Tinuphant",
  "Tabri",
  "Wesyl",
  "Ingdeh",
  "Esha",
  "Rinne",
  "Mandedhel",
  "Bregae",
  "Varrandir",
  "Elda",
  "Sobeleg",
  "Hadthorn",
  "Gimal",
  "Rafuphor",
  "Dwyriel",
  "Morilren",
  "Elran",
  "Elenadan",
  "Traior",
  "Aldeh",
  "Pa",
  "Curod",
  "Norceleb",
  "Shaphia",
  "Rodthir",
  "Teto",
  "Lethrin",
  "Aranmar",
  "Liaphia",
  "Borrond",
  "Sartae",
  "Lorso",
  "Jus",
  "Nerril",
  "Ralia",
  "Rodhal",
  "Aero",
  "Lia",
  "Viusthorn",
  "Cirvarr",
  "Resriannim",
  "Vanimor",
  "Rauilasel",
  "Winggor",
  "Onidriel",
  "Rastae",
  "Rianril",
  "Gae",
  "Thalionran",
  "Elle",
  "Shialren",
  "Rerian",
  "Briimorwe",
  "Hala",
  "Cego",
  "Aranmal",
  "Riahal",
  "Bornlee",
  "Draneie",
  "Cirra",
  "Ethwing",
  "Halra",
  "Fining",
  "Nasshim",
  "Curuenmoril",
  "Thifeu",
  "Ririn",
  "Daeaeg",
  "Imorhal",
  "Thalioncele",
  "Thetor",
  "Shamal",
  "Cirtha",
  "Cirro",
  "Torlad",
  "Belwe",
  "Lalince",
  "Lesra",
  "Xacu",
  "Eres",
  "Rionbel",
  "Thalrin",
  "Nasvius",
  "Lasrond",
  "Cudal",
  "Kur",
  "Rordan",
  "Mielimgor",
  "Tororrond",
  "Rorioruil",
  "Dalnas",
  "Ras",
  "Linle",
  "Marja",
  "Gnorel",
  "Ulren",
  "Thornha",
  "Dhroshal",
  "Drillos",
  "Lite",
  "Wingdal",
  "Edhelel",
  "Taeri",
  "Malthand",
  "Rinmai",
  "Wingmal",
  "Viusdril",
  "Giladan",
  "Grielev",
  "Laty",
  "Curu",
  "Rod",
  "Lanor",
  "Galrin",
  "Cirshan",
  "Bregeth",
  "Etham",
  "Dhrosmith",
  "Hirshi",
  "Wethos",
  "Edhelta",
  "Rondma",
  "Rodvius",
  "Vaja",
  "Malmiel",
  "Maiadan",
  "Adanborn",
  "Draneleth",
  "Vavo",
  "Alir",
  "Ethve",
  "Feutinu",
  "Rendis",
  "Dekig",
  "Klerog",
  "Urug",
  "Glugrut",
  "Grizur",
  "Keukorg",
  "Nutekohr",
  "Oag",
  "Trinazur",
  "Bralegut",
  "Narek",
  "Drorub",
  "Vreruk",
  "Neth",
  "Nexx",
  "Negrog",
  "Nekor",
  "Valmi",
  "Dotti",
  "Hippa",
  "Chibs",
  "Mitts",
  "Mitten",
  "Dorma",
  "Kornoth",
  "Mooth",
  "Maat",
  "Breni",
  "Zoma",
  "Nessik",
  "Hofi",
  "Meto",
  "Hali",
  "Domor",
  "Werag",
  "Asirk",
  "Tredugark",
  "Olokur",
  "Oirek",
  "Esikork",
  "Zuruk",
  "Zirek",
  "Grarg",
  "Kakag",
  "Bloruk",
  "Bumegruk",
  "Anikor",
  "Vuuzag",
  "Britark",
  "Giorg",
  "Urag",
  "Brorob",
  "Ugrot",
  "Wigut",
  "Egrut",
  "Gekuzur",
  "Dukagrok",
  "Gruezar",
  "Blugirag",
  "Brauk",
  "Hoon",
  "Garrachi",
  "Zote",
  "Zabiusu",
  "Bunne",
  "Travy",
  "Trav",
  "Unknown",
  "Rain",
  "Sab",
  "Nay",
  "Oneda",
  "Nole",
  "Ski",
  "Ornish",
  "Husaria",
  "Onion",
  "Demo",
  "Dramas",
  "Cesi",
  "Narook",
  "Sharook",
  "Carook",
  "Delk",
  "Helonim",
  "Ronphia",
  "Dronenye",
  "Adonlo",
  "Xir",
  "Altaeresadon",
  "Zaza",
  "Zir",
  "Nafk",
  "Gorne",
  "Majavid",
  "Koba",
  "Noba",
  "Joba",
  "Soba",
  "Roba",
  "Zoba",
  "Goba",
  "Yoba",
  "Nooth",
  "Mith",
  "Malak",
  "Mozz",
  "Desz",
  "Denoss",
  "Malj",
  "Magos",
  "Metzi",
  "Derk",
  "Goose",
  "Brinas",
  "Elaeg",
  "Bri",
  "Lien",
  "Varlos",
  "Rose",
  "Resli",
  "Aerin",
  "Gadal",
  "Fanre",
  "Leerom",
  "Rodgor",
  "Ralos",
  "Goion",
  "Xadal",
  "Quenner",
  "Rafin",
  "Themiel",
  "Kelto",
  "Feuner",
  "Maeoni",
  "Rorthel",
  "Thandriel",
  "Sylthas",
  "Varor",
  "Rohirfan",
  "Thandthe",
  "Dielma",
  "Andriel",
  "Thosborn",
  "Nekith",
  "Thalbo",
  "Vaarfin",
  "Mashim",
  "Veae",
  "Anorror",
  "Merilceleb",
  "Thornthal",
  "Jusaeg",
  "Lialin",
  "Sylthir",
  "Rohirshim",
  "Traionta",
  "Elli",
  "Narlos",
  "Nasdrane",
  "Tothe",
  "Gilpa",
  "Aemara",
  "Leonce",
  "Efind",
  "Nera",
  "Gallas",
  "Vaae",
  "Wenshi",
  "Maril",
  "Finriavarr",
  "Loranior",
  "Rionuil",
  "Galadh",
  "We",
  "Bodhel",
  "Thalra",
  "Dordrel",
  "Duiltarra",
  "Thornlia",
  "Leongil",
  "Griel",
  "Celede",
  "Thornglor",
  "Dranenas",
  "Dindar",
  "Golmothlos",
  "Mandve",
  "Thadis",
  "Grielfe",
  "Rielrin",
  "Aldir",
  "Phantdir",
  "Daedhel",
  "Fegal",
  "Raha",
  "Draneriel",
  "Sarphant",
  "Il",
  "Nasthal",
  "Dolgil",
  "Telin",
  "Satar",
  "Daeriel",
  "Loran",
  "Lodu",
  "Lordhros",
  "Curuuil",
  "Lafind",
  "Mithrien",
  "Dielazthor",
  "Vaaram",
  "Amarrom",
  "Leonne",
  "Randirthas",
  "Findrom",
  "Lasleth",
  "Lethdiel",
  "Thurinrian",
  "Mathdis",
  "Altaran",
  "Vashjvanmith",
  "Hirvo",
  "Golrin",
  "Fupa",
  "Eartoror",
  "Gaanor",
  "Grieil",
  "Maedan",
  "Lalthurin",
  "Uillee",
  "Dorionli",
  "Lasve",
  "Iero",
  "Nyeduil",
  "Rienthand",
  "Dephia",
  "Race",
  "Gilear",
  "Ilam",
  "Nedis",
  "Losmorilaz",
  "Malthas",
  "Erilfelathal",
  "Dannye",
  "Ratae",
  "Ulgriel",
  "Mor",
  "Alil",
  "Dielal",
  "Gols",
  "Gollix",
  "Gallox",
  "Galaxo",
  "Galaxis",
  "Galaxa",
  "Gaxa",
  "Loslos",
  "Gael",
  "Rortho",
  "Dirre",
  "Vaarror",
  "Weae",
  "Liaar",
  "Mothrin",
  "Rohirnas",
  "Uilasfan",
  "Penree",
  "Ingdaemand",
  "Leedan",
  "Thalnor",
  "Liaphant",
  "Del",
  "Naralta",
  "Carthi",
  "Ranle",
  "Eabeleg",
  "Ielvaar",
  "Vashjar",
  "Disras",
  "Thresdra",
  "Drinla",
  "Thorngil",
  "Duillee",
  "Dehran",
  "Eththal",
  "Dielthal",
  "Nasil",
  "Imordra",
  "Imwen",
  "Ereseres",
  "Thaldor",
  "Dhonha",
  "Northa",
  "Disar",
  "Anorthas",
  "Vashjmar",
  "Rathal",
  "Normai",
  "Gortororkhan",
  "Leskur",
  "Rielion",
  "Kraesda",
  "Raen",
  "Adandin",
  "Losvashj",
  "Rordath",
  "Lalpenwen",
  "Amli",
  "Phorvo",
  "Fan",
  "Releth",
  "Lidu",
  "Lialia",
  "Vartari",
  "Dranemoth",
  "Dirpa",
  "Drelmath",
  "Nasthe",
  "Hal",
  "Oni",
  "Altathi",
  "Masael",
  "Phantnye",
  "Megnor",
  "Dhrosnas",
  "Thitho",
  "Uildir",
  "Marmor",
  "Meril",
  "Ultinu",
  "Rasce",
  "Shimphant",
  "Finas",
  "Thraneril",
  "Gwinmith",
  "Ingga",
  "Thresedhel",
  "Thedalar",
  "Fin",
  "Dwyrtor",
  "Ranthan",
  "Vael",
  "Cafin",
  "Uille",
  "Drisril",
  "Losthel",
  "Gwinas",
  "Raslo",
  "Drilfind",
  "Thirra",
  "Resle",
  "Suquen",
  "Lesvanthal",
  "Vanazil",
  "Nasle",
  "Thathane",
  "Lator",
  "Drinren",
  "Khandor",
  "Rethjus",
  "Drilmal",
  "Shitoror",
  "Wethordrel",
  "Fanil",
  "Phiata",
  "Thalion",
  "Earhir",
  "Lale",
  "Randuil",
  "Zenbri",
  "Eldir",
  "Laeril",
  "Gafe",
  "Rosar",
  "Nasdral",
  "Ediel",
  "Nedal",
  "Brilo",
  "Aranel",
  "Marlos",
  "Ranmath",
  "Viusdhel",
  "Lafin",
  "Sharon",
  "Thranmith",
  "Meev",
  "Ranrinbreg",
  "Hel",
  "Arod",
  "Vashjel",
  "Thorncar",
  "Vemoril",
  "Saelne",
  "Haledhel",
  "Helfela",
  "Shala",
  "Grielshan",
  "Tariree",
  "Le",
  "Raleon",
  "Thorn",
  "The",
  "Renkur",
  "Nordriel",
  "Zenra",
  "Kraessael",
  "Drisda",
  "Thirrond",
  "Wego",
  "Brikraes",
  "Rodel",
  "Rommi",
  "Raar",
  "Lemaraquen",
  "Lerin",
  "Thaldol",
  "Rildral",
  "Dehoni",
  "Thorndor",
  "Ransar",
  "Toroni",
  "Wingtae",
  "Dhrosme",
  "Daththorn",
  "Peneres",
  "Tae",
  "Beldan",
  "Rasboa",
  "Enron",
  "Mithhal",
  "Nas",
  "Ugnakh",
  "Zocklurtz",
  "Dralurz",
  "Radlukorc",
  "Noshu",
  "Lugdrog",
  "Thosda",
  "Krimluk",
  "Kilgrat",
  "Bugrog",
  "Morah",
  "Bruk",
  "Glughrish",
  "Burzun",
  "Rokmuz",
  "Zugdush",
  "Lukgor",
  "Rumthulrosh",
  "Radgrel",
  "Lurtzco",
  "Olgblorg",
  "Thakzum",
  "Nazmor",
  "Morrok",
  "Kashnakh",
  "Shnagash",
  "Zogthug",
  "Lukvamau",
  "Gumurz",
  "Gudu",
  "Dakhor",
  "Gashva",
  "Morgrim",
  "Ubbru",
  "Olgsha",
  "Ulurtz",
  "Bolga",
  "Skuma",
  "Gashshur",
  "Thoslug",
  "Orcthok",
  "Dorgnazg",
  "Laghar",
  "Oggrat",
  "Skaborc",
  "Dakhgimb",
  "Orgra",
  "Roggrosh",
  "Ufgor",
  "Radnarg",
  "Grelgrat",
  "Balctul",
  "Gruntbolg",
  "Nagtu",
  "Lukthak",
  "Crou",
  "Zock",
  "Harcro",
  "Ahar",
  "Tuzug",
  "Hrishva",
  "Shaggu",
  "Orzdra",
  "Glukron",
  "Buck",
  "Lurtzthrum",
  "Bugthug",
  "Bagtan",
  "Bolgkrim",
  "Ognarg",
  "Bolckgrom",
  "Bolgel",
  "Lugzog",
  "Lug",
  "Thrumju",
  "Harolg",
  "Hrishmog",
  "Baag",
  "Dishgor",
  "Sujoanwine",
  "Beorthlifridwine",
  "Daegarripa",
  "Grimesctoniel",
  "Reginmacald",
  "Phielauleofan",
  "Iswithvia",
  "Samnathrobruthly",
  "Theodgrimtoda",
  "Maceoleli",
  "Wilmacfastber",
  "Edciapadun",
  "Jeffchaelri",
  "Joanbrandforth",
  "Vinciason",
  "Sanchaelfled",
  "Elfsereardnya",
  "Ryfasthewsyl",
  "Haleecy",
  "Waldbrytordruth",
  "Thyferordmerie",
  "Beorndanlamen",
  "Crowsephbandoma",
  "Marknielegelke",
  "Redelfbeoga",
  "Ordancar",
  "Marferfrithwillee",
  "Tolrictolwig",
  "Isiam",
  "Bethisenjackred",
  "Ardearahdoc",
  "Nathwinechrismar",
  "Micuthridvin",
  "Ceolanlacja",
  "Hewgifuanadel",
  "Ronhamisum",
  "Cyealanar",
  "Chelricwald",
  "Ferthtolclafled",
  "Garthyorah",
  "Kesungwald",
  "Seanrie",
  "Dictermarnas",
  "Riiwarujophie",
  "Viaminathric",
  "Kevgormamark",
  "Evervinferum",
  "Lacthonyaldadel",
  "Nyaedli",
  "Mannwineshau",
  "Naldgarwulfrol",
  "Fledsephbrandmi",
  "Jogormajoan",
  "Lettecwen",
  "Vellriely",
  "Caraldbethchel",
  "Cajaleofred",
  "Gardroldun",
  "Mensonjoan",
  "Anviaeal",
  "Frealenmax",
  "Rolmescar",
  "Geter",
  "Gardmasly",
  "Lauhamric",
  "Serecome",
  "Rahananne",
  "Joredbri",
  "Rahjarol",
  "Josanrob",
  "Menleofuniel",
  "Orddanvell",
  "Egarwaruever",
  "Rorich",
  "Bacas",
  "Kevcharkev",
  "Jake",
  "Cavid",
  "Concrowfrid",
  "Casmond",
  "Donmacchel",
  "Fertommeschard",
  "Heskeforth",
  "Holbeornlas",
  "Stehetydon",
  "Isentineceoald",
  "Seregakimleofan",
  "Lafcuth",
  "Kebeothyrocward",
  "Sothoward",
  "Harolacarhes",
  "Masijohnfrid",
  "Garethel",
  "Jaegartomes",
  "Dinoshabeo",
  "Tanaldrahmac",
  "Ronbethtonaferum",
  "Leesonandra",
  "Wulfhelmmuel",
  "Barmitadelcwen",
  "Saraheregeor",
  "Nandicneth",
  "Dasa",
  "Winemuellaurob",
  "Phierahcuth",
  "Richrol",
  "Lasbando",
  "Sovellpa",
  "Escwensa",
  "Sigpabras",
  "Merivin",
  "Tadralett",
  "Kakewen",
  "Thrythra",
  "Andpherthony",
  "Ancyn",
  "Dasancwen",
  "Riarielin",
  "Stesamda",
  "Rahnasan",
  "Laulett",
  "Cenberbrassara",
  "Wigferlett",
  "Linrobfrithcwen",
  "Macorahelf",
  "Samsigdabeorn",
  "Wardadelpherjack",
  "Joangarni",
  "Beorthceolkacuth",
  "Rethildisha",
  "Gardesckesa",
  "Helmrichsylan",
  "Ogar",
  "Richjeffmarmalee",
  "Ejorich",
  "Nathsaniu",
  "Lacdodtri",
  "Retcyncar",
  "Ferumdicethel",
  "Annezadic",
  "Jenisum",
  "Kaegar",
  "Chaeldoke",
  "Stanchael",
  "Hildialddic",
  "Donkebard",
  "Suforththo",
  "Steadelron",
  "Gifuingta",
  "Heredo",
  "Retni",
  "Serealddeb",
  "Bethba",
  "Johnmaxric",
  "Kensa",
  "Phiewiselee",
  "Leeburja",
  "Dassungbarcar",
  "Maxsylmencon",
  "Rengrimmax",
  "Dorlad",
  "Gildir",
  "Mothleth",
  "Ri",
  "Dismal",
  "Nall",
  "Uilras",
  "Vome",
  "Danmae",
  "Cu",
  "Uilosmal",
  "Cele",
  "Morshi",
  "Khanaran",
  "Briuilas",
  "Direl",
  "Galvo",
  "Delev",
  "Thor",
  "Lalia",
  "Drielbo",
  "Kraes",
  "Celete",
  "Rasior",
  "Godol",
  "Ranga",
  "Dire",
  "Helim",
  "Lesrond",
  "Sarron",
  "Rinphia",
  "Lethhal",
  "Dranenye",
  "Adanlo",
  "Rilbreg",
  "Circu",
  "Altaeresadan",
  "Ilel",
  "Nasthorn",
  "Alhad",
  "Eare",
  "Mavashj",
  "Shavius",
  "Weda",
  "Wetae",
  "Thanefe",
  "Lorshimlos",
  "Edhelingva",
  "Nallrond",
  "Rethimgorion",
  "Thanegol",
  "Leeren",
  "Thorphor",
  "Rion",
  "Randirle",
  "Helca",
  "Drelbreg",
  "Galar",
  "Soro",
  "Safan",
  "Thirphant",
  "Car",
  "Miiso",
  "Oorz",
  "Gratga",
  "Mog",
  "Lugzug",
  "Chaktriggbol",
  "Hargor",
  "Morpruk",
  "Burzrok",
  "Rumgrunt",
  "Nakh",
  "Mogzum",
  "Radrok",
  "Krimdrak",
  "Jugimb",
  "Dufor",
  "Nea",
  "Balblorg",
  "Gimbtul",
  "Hargkash",
  "Bugbruk",
  "Dakhbra",
  "Lagu",
  "Gorbolckel",
  "Balcsnarl",
  "Thakdrog",
  "Lukbruk",
  "Skumlug",
  "Sharkgluk",
  "Burzuz",
  "Dakhka",
  "Garmhed",
  "Rokmor",
  "Murzrum",
  "Grommor",
  "Snarllu",
  "Gashu",
  "Bolgluk",
  "Umog",
  "Thurgmash",
  "Durduz",
  "Ahrad",
  "Muzmog",
  "Thuggu",
  "Mashdush",
  "Dushga",
  "Kros",
  "Orva",
  "Dubug",
  "Sharklug",
  "Co",
  "Dorgbur",
  "Thulthul",
  "Goththug",
  "Dakhrogg",
  "Ongsnarl",
  "Throd",
  "Gromugdog",
  "Gashbra",
  "Likmor",
  "Garhurtz",
  "Rogdush",
  "Zugrom",
  "Nargblorg",
  "Thoszun",
  "Kildu",
  "Vasela",
  "Selbur",
  "Luknaz",
  "Zudorg",
  "Durka",
  "Lugmor",
  "Grigluk",
  "Brugrunt",
  "Nazggra",
  "Noshgim",
  "Garrend",
  "Lurtz",
  "Grilurtz",
  "Grelgrunt",
  "Dushgrat",
  "Buzgarm",
  "Selgul",
  "Gromju",
  "Baagmau",
  "Shnaggro",
  "Nargu",
  "Negluk",
  "Duzlurtz",
  "Gratorz",
  "Thuldush",
  "Zhulzhul",
  "Ongmog",
  "Mashzum",
  "Lurzbaag",
  "Rorum",
  "Chakdal",
  "Thurggarm",
  "Thugcro",
  "Trigggeyka",
  "Maubur",
  "Bauf",
  "Lurzglukburz",
  "Grim",
  "Gor",
  "Nazgor",
  "Gragol",
  "Gulduz",
  "Rokgul",
  "Ronluk",
  "Drao",
  "Bruklurtz",
  "Radnaz",
  "Crogul",
  "Golglug",
  "Goldorg",
  "Codrak",
  "Tanka",
  "Lukgoth",
  "Snarlgor",
  "Murgor",
  "Elrogshur",
  "Hurzogog",
  "Ua",
  "Rad",
  "Geythrod",
  "Tulug",
  "Ong",
  "Dahkgor",
  "Krimgrimzu",
  "Duzka",
  "Gorzu",
  "Nakhrok",
  "Ithug",
  "Gothgar",
  "Bolgdal",
  "Lukthug",
  "Luklug",
  "Gashrogg",
  "Adakh",
  "Grimgar",
  "Juthrum",
  "Garbu",
  "Goru",
  "Utriggnosh",
  "Lurtzzhul",
  "Gromthrum",
  "Dorgong",
  "Vagor",
  "Romau",
  "Muz",
  "Rendhrish",
  "Likgagu",
  "Urkkrim",
  "Lugoth",
  "Mordrak",
  "Chakmog",
  "Kil",
  "Karggoth",
  "Karglurtz",
  "Zogthos",
  "Sel",
  "Gullurtz",
  "Gashmog",
  "Golhrish",
  "Dagluk",
  "Butu",
  "Nackah",
  "Throdga",
  "Kamau",
  "Chakkargner",
  "Glukgrat",
  "Gashglukbaag",
  "Glukrog",
  "Burzthulhed",
  "Gratnack",
  "Ashdan",
  "Ashluk",
  "Nazrum",
  "Drauz",
  "Orzong",
  "Hargel",
  "Radlug",
  "Naz",
  "Krimzock",
  "Rokkash",
  "Narglurtz",
  "Shurbruk",
  "Pruk",
  "Balcduf",
  "Olggrom",
  "Glukah",
  "Gashrend",
  "Ugrom",
  "Arok",
  "Chelphie",
  "Mancon",
  "Fast",
  "Das",
  "Annsan",
  "Freato",
  "Bardgar",
  "Baldmen",
  "Fridchael",
  "Locry",
  "Thaschet",
  "Vellar",
  "Reginliam",
  "Anwine",
  "Gathas",
  "Wulftri",
  "Mardod",
  "Ni",
  "Lastine",
  "Cani",
  "Eded",
  "Dajoan",
  "Thordic",
  "Wardkev",
  "Hew",
  "Usere",
  "Marmakim",
  "Sandas",
  "Thrythsan",
  "Tineni",
  "Nemeri",
  "Eadrol",
  "Lafthyfortin",
  "Anneal",
  "Cwenarsa",
  "Gaviachris",
  "Man",
  "Nibardge",
  "Lydan",
  "Jenca",
  "Jaesc",
  "Freali",
  "Grimdo",
  "Jackjoan",
  "Dopa",
  "Hesmarmahal",
  "Drytnath",
  "Aret",
  "Joantom",
  "Bartomcwen",
  "Mitgifu",
  "Eli",
  "Jobur",
  "Chaelhelm",
  "Crowchar",
  "Saraferum",
  "Red",
  "Thasla",
  "Bald",
  "Beornnath",
  "Dinolac",
  "Rahtim",
  "Reginrich",
  "Clawerd",
  "Arddun",
  "Garcyn",
  "Ciavin",
  "Masfled",
  "Rocwen",
  "Santol",
  "Ley",
  "Marmason",
  "Rahsan",
  "Kenbard",
  "Vidorah",
  "Wilfast",
  "Laf",
  "Ruthnan",
  "Garrah",
  "Ethelmax",
  "Jaton",
  "Roleli",
  "Swithea",
  "Beorthliam",
  "Roynas",
  "Cuthdino",
  "Ardanne",
  "Marchard",
  "Bertchard",
  "Lidon",
  "O",
  "Ceolsephleofu",
  "Hamnath",
  "Kevsyl",
  "Bras",
  "Char",
  "Ferthcas",
  "Johnwise",
  "Orahand",
  "Redni",
  "Tolni",
  "Cafrid",
  "Elfchet",
  "Wisefrid",
  "Tine",
  "Nihes",
  "Brytjen",
  "Markchet",
  "Jen",
  "Thonylau",
  "Ceolea",
  "E",
  "Lauan",
  "Fastbard",
  "UcaRontaroy",
  "Brandja",
  "Irah",
  "Eri",
  "Tyret",
  "Leybrand",
  "Neruth",
  "Ven",
  "Velldic",
  "Liamesc",
  "Ronrid",
  "Cwen",
  "Waruing",
  "Mando",
  "Acarferth",
  "Ealred",
  "Lin",
  "Johnria",
  "Aldloc",
  "Hesjohndon",
  "Manley",
  "Sephnya",
  "Redris",
  "Ferthsha",
  "Fledjoan",
  "Jao",
  "Muelda",
  "Venlett",
  "Pe",
  "Rowig",
  "Reginchel",
  "Nanu",
  "Escle",
  "Fer",
  "Roywil",
  "Bertinelay",
  "Lesven",
  "Geberi",
  "Guthmas",
  "Cwenter",
  "Lauordgar",
  "Hildiwilham",
  "Ferumfreada",
  "Lacstan",
  "Lettchare",
  "Joanbeorth",
  "Ronwaru",
  "Holpe",
  "Orahhefrith",
  "Retjackrob",
  "Casingbrasric",
  "Chelleofuneth",
  "Dasonthaesa",
  "Mesroholvell",
  "Ancla",
  "Baldnascon",
  "Rycanald",
  "Fastja",
  "Lafdebanne",
  "Vellseph"
];
let dataFactory;
let dataContract;
let factories;
let args;
let contracts;
let address;
let buildings = [
  {
    area: 0,
    location: 2,
  },
  {
    area: 0,
    location: 1,
  },
  {
    area: 0,
    location: 3,
  },
  {
    area: 0,
    location: 4,
  },
  {
    area: 0,
    location: 5,
  },
  {
    area: 0,
    location: 6,
  },
  {
    area: 0,
    location: 7,
  }
];
let npcs = [
  {
    area: 0,
    level: 2
  }
];
let enemies = [
  {
    area: 0,
    level: 2,
    species: 1
  },
  {
    area: 0,
    level: 2,
    species: 1
  },
  {
    area: 0,
    level: 2,
    species: 1
  },
  {
    area: 0,
    level: 2,
    species: 1
  },
  {
    area: 0,
    level: 2,
    species: 1
  }
];
let equipment = [
  // VALUE IS IRRELEVANT
  0,
  0
]

async function getAccounts() {
  const accounts = await hre.ethers.getSigners();
  address = accounts[1].address;
}

async function deploy() {
  dataFactory = await hre.ethers.getContractFactory("ERC42069Data");
  dataContract = await dataFactory.deploy();
  await dataContract.deployed();
  factories = [
    await hre.ethers.getContractFactory("ERC20Credits"),
    await hre.ethers.getContractFactory("ERC42069"),
    await hre.ethers.getContractFactory("ERC42069Helper"),
    await hre.ethers.getContractFactory("ERC42069Reverts"),
    await hre.ethers.getContractFactory("GameMaster"),
    await hre.ethers.getContractFactory("GreatFilter"),
    await hre.ethers.getContractFactory("Expansion0Master"),
    await hre.ethers.getContractFactory("ERC42069DataHelper"),
    await hre.ethers.getContractFactory("NameGenerator"),
    await hre.ethers.getContractFactory("MintMaster")
  ];
  args = [
    ["Pixel Credits", "CREDITS", dataContract.address],
    ["Pixel Asset", "PIXEL", dataContract.address],
    [dataContract.address],
    [dataContract.address],
    [dataContract.address],
    [dataContract.address],
    [dataContract.address],
    [dataContract.address],
    [dataContract.address],
    [dataContract.address]
  ];
  contracts = [
    await factories[0].deploy(...args[0]),
    await factories[1].deploy(...args[1]),
    await factories[2].deploy(...args[2]),
    await factories[3].deploy(...args[3]),
    await factories[4].deploy(...args[4]),
    await factories[5].deploy(...args[5]),
    await factories[6].deploy(...args[6]),
    await factories[7].deploy(...args[7]),
    await factories[8].deploy(...args[8]),
    await factories[9].deploy(...args[9])
  ];
  await contracts[0].deployed();
  await contracts[1].deployed();
  await contracts[2].deployed();
  await contracts[3].deployed();
  await contracts[4].deployed();
  await contracts[5].deployed();
  await contracts[6].deployed();
  await contracts[7].deployed();
  await contracts[8].deployed();
  await contracts[9].deployed();
}

async function setup() {
  await setGameSettings();
  await setConsumableType();
  await setAddresses();
  await setWorld();
}

async function setAddresses() {
  console.log("ERC42069DATA", dataContract.address);
  console.log("ERC20CREDITS", contracts[0].address);
  console.log("ERC42069", contracts[1].address);
  console.log("ERC42069HELPER", contracts[2].address);
  console.log("ERC42069REVERTS", contracts[3].address);
  console.log("GAMEMASTER", contracts[4].address);
  console.log("GREATFILTER", contracts[5].address);
  console.log("EXPANSION0MASTER", contracts[6].address);
  console.log("ERC42069DATAHELPER", contracts[7].address);
  console.log("NAMEGENERATOR", contracts[8].address);
  console.log("MINTMASTER", contracts[9].address);
  console.log("WEB3BYPASSER", "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266");
  await dataContract.setAA("ERC20CREDITS", contracts[0].address);
  await dataContract.setAA("ERC42069", contracts[1].address);
  await dataContract.setAA("ERC42069HELPER", contracts[2].address);
  await dataContract.setAA("ERC42069REVERTS", contracts[3].address);
  await dataContract.setAA("GAMEMASTER", contracts[4].address);
  await dataContract.setAA("GREATFILTER", contracts[5].address);
  await dataContract.setAA("EXPANSION0MASTER", contracts[6].address);
  await dataContract.setAA("ERC42069DATAHELPER", contracts[7].address);
  await dataContract.setAA("NAMEGENERATOR", contracts[8].address);
  await dataContract.setAA("MINTMASTER", contracts[9].address);
  await dataContract.setAA("WEB3BYPASSER", "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266");
}

async function setGameSettings() {
  await dataContract.setGS("MAXTOTALLEVEL", 99);
  await dataContract.setGS("MAXTOTALHEALTH", 1000000);
  await dataContract.setGS("MAXTOTALENERGY", 5000);
  await dataContract.setGS("MAXTOTALSTATS", 1000);
  await dataContract.setGS("MAXITEMSLOTS", 9);
  await dataContract.setGS("MAXITEMHEALTH", 100);
  await dataContract.setGS("MAXITEMENERGY", 100);
  await dataContract.setGS("MAXITEMSTATS", 20);
  await dataContract.setGS("STARTINGHEALTH", 100);
  await dataContract.setGS("STARTINGENERGY", 100);
  await dataContract.setGS("STARTINGSTATS", 10);
  await dataContract.setGS("MAXLEVELSTATS", 3);
  await dataContract.setGS("BREEDINGRESET", 3600);
  await dataContract.setGS("FIGHTEARNING", 10);
  await dataContract.setGS("FIGHTEXPERIENCE", 20);
  await dataContract.setGS("LEVELUP", 1000);
  await dataContract.setGS("MAXPRODUCTION", 20);
  await dataContract.setGS("PRODUCTIONRESET", 600);
  await dataContract.setGS("CHARACTERCOST", 100);
  await dataContract.setGS("EQUIPPABLECOST", 500);
  await dataContract.setGS("PRODUCTIONCOST", 2500);
  await dataContract.setGS("BUILDINGCOST", 10000);
  await dataContract.setGS("EXPANDBUILDINGCOST", 5000);
  await dataContract.setGS("AREABLOCKSIZE", 16);
  await dataContract.setGS("AREASIZE", (16 * 16));
  await dataContract.setGS("MAXAREAS", 4096);
  await dataContract.setGS("QUESTTIMER", 3600);
  await dataContract.setGS("QUESTREWARD", 10);
}

async function setConsumableType() {
    await dataContract.setGD("CONSUMABLETYPE", 0, "HEALTHRESTORE", 1, "SETUP");
    await dataContract.setGD("CONSUMABLETYPE", 1, "ENERGYRESTORE", 1, "SETUP");
    await dataContract.setGD("CONSUMABLETYPE", 2, "STRENGTHBOOST", 1, "SETUP");
    await dataContract.setGD("CONSUMABLETYPE", 3, "DEXTERITYBOOST", 1, "SETUP");
    await dataContract.setGD("CONSUMABLETYPE", 4, "INTELLIGENCEBOOST", 1, "SETUP");
    await dataContract.setGD("CONSUMABLETYPE", 5, "CHARISMABOOST", 1, "SETUP");
    await dataContract.setGD("CONSUMABLETYPE", 6, "HEALTHBOOST", 1, "SETUP");
    await dataContract.setGD("CONSUMABLETYPE", 7, "ENERGYBOOST", 1, "SETUP");
    await dataContract.setGD("CONSUMABLETYPE", 8, "BREEDINGRESET", 1, "SETUP");
}

async function setWorld() {
  await addNames();
}

async function setFreeProducables() {
  await contracts[9].generateProducable(1, 0, 1);
  await contracts[9].generateProducable(1, 1, 1);
  await contracts[9].generateProducable(1, 2, 1);
  await contracts[9].generateProducable(1, 3, 1);
  await contracts[9].generateProducable(1, 4, 1);
  await contracts[9].generateProducable(1, 5, 1);
  await contracts[9].generateProducable(1, 6, 1);
  await contracts[9].generateProducable(1, 7, 1);
  await contracts[9].generateProducable(1, 8, 1);
}

async function setFreeCharacters() {
  const address = "0xbcd4042de499d14e55001ccbb24a551f3b954096";
  await contracts[9].generateEquippedCharacter(0, 0, 0, address);
  await contracts[9].generateEquippedCharacter(1, 0, 0, address);
  await contracts[9].generateEquippedCharacter(1, 0, 0, address);
  await contracts[9].generateEquippedCharacter(1, 0, 0, address);
  await contracts[9].generateCharacter(1, 2, 0, 0, address);
  await contracts[9].generateCharacter(1, 2, 0, 0, address);
  await contracts[9].generateCharacter(1, 2, 0, 0, address);
  await contracts[9].generateCharacter(1, 2, 0, 0, address);
  await contracts[9].generateCharacter(33, 2, 0, 0, address);
  await contracts[9].generateEquippedCharacter(1, 0, 0, address);
  await contracts[9].generateEquippedCharacter(1, 0, 0, address);
  await contracts[9].generateEquippedCharacter(1, 0, 0, address);
  await contracts[9].generateEquippedCharacter(1, 0, 0, address);
  await contracts[9].generateEquippedCharacter(1, 0, 0, address);
  await contracts[9].generateCharacter(33, 2, 0, 0, address);
  await contracts[9].generateCharacter(33, 1, 0, 0, address);
  await contracts[9].generateCharacter(66, 1, 0, 0, address);
  await contracts[9].generateCharacter(34, 1, 0, 0, address);
  await contracts[9].generateCharacter(70, 1, 0, 0, address);
  await contracts[9].generateEquippedCharacter(1, 0, 0, address);
  await contracts[9].generateEquippedCharacter(1, 0, 0, address);
  await contracts[9].generateEquippedCharacter(1, 0, 0, address);
  await contracts[9].generateEquippedCharacter(1, 0, 0, address);
}

async function setFreeRoamingCharacters() {
  const index = 1;
    await contracts[9].generateEquippedCharacter(1 * index, 0, 0, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateEquippedCharacter(5 * index, 0, 0, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateEquippedCharacter(3 * index, 0, 0, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateEquippedCharacter(2 * index, 0, 0, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateEquippedCharacter(1 * index, 0, 0, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateEquippedCharacter(5 * index, 0, 0, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateEquippedCharacter(3 * index, 0, 0, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateEquippedCharacter(2 * index, 0, 0, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateEquippedCharacter(1 * index, 0, 0, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateEquippedCharacter(5 * index, 0, 0, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateEquippedCharacter(3 * index, 0, 0, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateEquippedCharacter(2 * index, 0, 0, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateEquippedCharacter(1 * index, 0, 0, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateEquippedCharacter(5 * index, 0, 0, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateEquippedCharacter(3 * index, 0, 0, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateEquippedCharacter(2 * index, 0, 0, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateEquippedCharacter(59, 0, 0, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(2 * (index % 14) + 1, 1, 1, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(3 * (index % 14) + 1, 0, 2, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(4 * (index % 14) + 1, 0, 2, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(5 * (index % 14) + 1, 0, 2, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(6 * (index % 14) + 1, 1, 1, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(7 * (index % 14) + 1, 1, 1, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(2 * (index % 14) + 1, 1, 1, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(3 * (index % 14) + 1, 0, 2, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(4 * (index % 14) + 1, 2, 2, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(5 * (index % 14) + 1, 2, 2, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(6 * (index % 14) + 1, 1, 1, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(7 * (index % 14) + 1, 1, 1, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(2 * (index % 14) + 1, 1, 1, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(3 * (index % 14) + 1, 0, 2, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(4 * (index % 14) + 1, 0, 2, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(5 * (index % 14) + 1, 2, 2, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(6 * (index % 14) + 1, 1, 1, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(7 * (index % 14) + 1, 1, 1, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(2 * (index % 14) + 1, 1, 1, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(3 * (index % 14) + 1, 0, 2, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(4 * (index % 14) + 1, 0, 2, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(5 * (index % 14) + 1, 0, 2, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(6 * (index % 14) + 1, 1, 1, index, "0x000000000000000000000000000000000000dEaD");
    await contracts[9].generateCharacter(7 * (index % 14) + 1, 1, 1, index, "0x000000000000000000000000000000000000dEaD");
}

async function setFreeConsumables() {
  await contracts[9].generateConsumable(200, 0, 1);
  await contracts[9].generateConsumable(200, 1, 1);
  await contracts[9].generateConsumable(200, 2, 1);
  await contracts[9].generateConsumable(200, 3, 1);
  await contracts[9].generateConsumable(200, 4, 1);
  await contracts[9].generateConsumable(200, 5, 1);
  await contracts[9].generateConsumable(200, 6, 1);
  await contracts[9].generateConsumable(200, 7, 1);
  await contracts[9].generateConsumable(200, 8, 1);
}

async function setFreeItems() {
  await contracts[9].generateEquippable(2, 0, 1);
  await contracts[9].generateEquippable(2, 1, 1);
  await contracts[9].generateEquippable(2, 2, 1);
  await contracts[9].generateEquippable(2, 3, 1);
  await contracts[9].generateEquippable(2, 4, 1);
  await contracts[9].generateEquippable(2, 5, 1);
  await contracts[9].generateEquippable(2, 6, 1);
  await contracts[9].generateEquippable(2, 7, 1);
  await contracts[9].generateEquippable(2, 8, 1);
}

async function setBuildings() {
  for (let index = 0; index < 10; index++) {
    await contracts[9].generateBuilding(0, index, 1);
  }
}

async function setNPCs() {
  for (let index = 0; index < npcs.length; index++) {
    await contracts[9].generateCharacter(npcs[index].level, 0, 1, npcs[index].area, "0x000000000000000000000000000000000000dEaD");
  }
}

async function setEnemies() {
  for (let index = 0; index < enemies.length; index++) {
    await contracts[9].generateCharacter(enemies[index].level, enemies[index].species, 2, enemies[index].area, "0x000000000000000000000000000000000000dEaD");
  }
}

async function addNames() {
    await contracts[8].addName(names.slice(0, 100));
    await contracts[8].addName(names.slice(100, 200));
    await contracts[8].addName(names.slice(200, 300));
    await contracts[8].addName(names.slice(300, 400));
    await contracts[8].addName(names.slice(400, 500));
    await contracts[8].addName(names.slice(500, 600));
    await contracts[8].addName(names.slice(600, 700));
    await contracts[8].addName(names.slice(700, 800));
    await contracts[8].addName(names.slice(800, 900));
    await contracts[8].addName(names.slice(900, 1000));
    await contracts[8].addName(names.slice(1000, 1100));
    await contracts[8].addName(names.slice(1100, 1200));
    await contracts[8].addName(names.slice(1200, 1300));
    await contracts[8].addName(names.slice(1300, 1400));
    await contracts[8].addName(names.slice(1400, 1500));
    await contracts[8].addName(names.slice(1500, 1600));
    await contracts[8].addName(names.slice(1600, 1700));
    await contracts[8].addName(names.slice(1700, 1800));
    await contracts[8].addName(names.slice(1800, 1900));
}

async function main() {
  await deploy();
  await getAccounts();
  await setup();
}

main()
  .then(() => {
    process.exit(0);
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
  